# Generated by Django 4.0.4 on 2022-06-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='fighters',
            field=models.ManyToManyField(through='data.BattleCharacter', to='data.character'),
        ),
    ]
